config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create]
    end
  end

  resource :profile, on: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
class Board < ApplicationRecord

    validates :title, presence: true
    validates :content, presence: true

    has_many :tasks, dependent: :destroy
    belongs_to :user
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  task_id    :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_comments_on_task_id  (task_id)
#  index_comments_on_user_id  (user_id)
#
class Comment < ApplicationRecord

    validates :content, presence: true

    belongs_to :task
    belongs_to :user
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id           :bigint           not null, primary key
#  birthday     :date
#  introdaction :text
#  nickname     :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord

    has_one_attached :avatar

    validates :nickname, presence: true

    belongs_to :user
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  limit_date :date             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_tasks_on_board_id  (board_id)
#  index_tasks_on_user_id   (user_id)
#
class Task < ApplicationRecord

    has_one_attached :eyecatch

    validates :title, presence: true
    validates :content, presence: true
    validates :limit_date, presence: true

    belongs_to :board
    belongs_to :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one :profile, dependent: :destroy

  delegate :birthday, :introdaction, to: :profile, allow_nil: true

  def prepare_profile
    profile || build_profile
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'face-24px.svg'
    end
  end

  def display_name
    profile&.nickname || self.email.split('@').first
  end

  def has_written?(board)
    boards.exists?(id: board.id)
  end

  def has_written_task?(task)
    tasks.exists?(id: task.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

    def index
        @boards = Board.all
    end

    def show
        @board = Board.find(params[:id])
        @tasks = @board.tasks
    end

    def new
        @board = current_user.boards.build
    end

    def create
        @board = current_user.boards.build(board_params)
        if @board.save
            redirect_to root_path, notice: '保存できました'
        else
            flash.now[:error] = '保存できませんでした'
            render :new
        end
    end

    def edit
        @board = current_user.boards.find(params[:id])
    end

    def update
        @board = current_user.boards.find(params[:id])
        if @board.update(board_params)
            redirect_to root_path, notice: '更新できました'
        else
            flash.now[:error] = '更新できませんでした'
            render :edit
        end
    end

    def destroy
        board = current_user.boards.find(params[:id])
        board.destroy!
        redirect_to root_path, notice: '削除されました'
    end

    private
        def board_params
            params.require(:board).permit(:title, :content)
        end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def new
        @board = Board.find(params[:board_id])
        @task = Task.find(params[:task_id])
        @comment = @task.comments.build
    end

    def create
        @board = Board.find(params[:board_id])
        @task = Task.find(params[:task_id])
        @comment = @task.comments.build(comment_params)
        @comment.user = current_user
        if @comment.save
            redirect_to board_task_path(@board, @task), notice: 'コメントしました'
        else
            flash.now[:error] = 'コメントできませんでした'
            render :new
        end
    end

    private 
        def comment_params
            params.require(:comment).permit(:content)
        end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!

    def show
        @profile = current_user.profile
    end

    def edit
        @profile = current_user.prepare_profile
    end

    def update
        @profile = current_user.prepare_profile
        @profile.assign_attributes(profile_params)
        if @profile.save
            redirect_to profile_path, notice: 'プロフィールが更新されました'
        else
            flash.now[:error] = 'プロフィールが更新できませんでした'
            render :edit
        end
    end

    private
        def profile_params
            params.require(:profile).permit(:avatar, :nickname, :introdaction, :birthday)
        end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

    def show
        @board = Board.find(params[:board_id])
        @task = Task.find(params[:id])
        @comments = @task.comments
    end

    def new
        @task = current_user.tasks.build
    end

    def create
        board = Board.find(params[:board_id])
        @task = board.tasks.build(task_params)
        @task.user = current_user
        if @task.save
            redirect_to board_path(board), notice: '保存されました'
        else
            flash.now[:error] = '保存できませんでした'
            render :new
        end
    end

    def edit
        @board = Board.find(params[:board_id])
        @task = current_user.tasks.find(params[:id])
    end

    def update
        @board = Board.find(params[:board_id])
        @task = current_user.tasks.find(params[:id])
        if @task.update(task_params)
            redirect_to board_task_path(@board, @task), notice: '更新できました'
        else
            flash.now[:error] = '更新できませんでした'
            render :edit
        end
    end

    def destroy
        @board = Board.find(params[:board_id])
        task = current_user.tasks.find(params[:id])
        task.destroy!
        redirect_to board_path(@board), notice: '削除されました'
    end

    private
        def task_params
            params.require(:task).permit(:title, :content, :limit_date, :eyecatch)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_form.html.haml
%ul
  - board.errors.full_messages.each do |message|
    %li= message    
= form_with(model: board, local: true) do |f|
  %div
    = f.label :title, 'Name'
  %div
    = f.text_field :title, class: 'text'
  %div
    = f.label :content, 'Description'
  %div
    = f.text_area :content
  %div
    = f.submit 'Submit', class: 'btn-primary'

app/views/boards/edit.html.haml
.container
  = render 'form', board: @board

app/views/boards/index.html.haml
.container
  %h2 All Boards
  - @boards.each do |board|
    = render 'commons/boards', board: board

  = link_to new_board_path do
    .new
      .new_title
        + Add new board

app/views/boards/new.html.haml
.container
  %h2 New Board
  
  = render 'form', board: @board

app/views/boards/show.html.haml
.container
  %h2= @board.title

  - @tasks.each do |task|
    = link_to board_task_path(@board, task) do
      .card
        - if task.eyecatch.attached?
          .card_image
            = image_tag task.eyecatch
        .card_section
          .card_section_title
            = task.title       
        .card_content  
          = task.content
        .card_detail
          = image_tag task.user.avatar_image

  = link_to new_board_task_path(@board) do
    .new
      .new_title
        + Add new card

app/views/comments/new.html.haml
.container
  %h2 New Comment

  %ul
  - @comment.errors.full_messages.each do |message|
    %li= message   
  = form_with(model: @comment, url: board_task_comments_path, local: true) do |f|
    %div
      = f.text_area :content
    %div
      = f.submit 'Submit', class: 'btn-primary'

app/views/commons/_boards.html.haml
= link_to board_path(board) do
  %div
    .card
      .card_section
        .card_section_title
          = board.title
      
        .board_detail_actions
        - if user_signed_in? && current_user.has_written?(board)
          .dropdown
            = image_tag 'Combined Shape.png', class: 'dropbtn'
            .dropdown-content.mini
              = link_to 'Edit', edit_board_path(board)
              = link_to 'Delete', board_path(board), data: { method: 'delete' , confirm: '本当に削除してもよろしいですか？'}
      .card_content  
        = board.content
      .card_detail
        = image_tag board.user.avatar_image

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TodoApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
  %body
    %header.header
      %p.header_pageTitle= link_to 'Boards', root_path
      - if user_signed_in?
        .dropdown  
          = image_tag current_user.avatar_image, class: 'header_logos', class: 'header_avatar'
          .dropdown-content.mini
            = link_to 'Prifile', profile_path
            = link_to 'Sign out', destroy_user_session_path, data: { method: 'delete' }
      - else
        = link_to 'Sign in', new_user_session_path, class: 'header_loginBtn'
      %hr
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield

app/views/profiles/edit.html.haml
.container
  %ul
  - @profile.errors.full_messages.each do |message|
    %li= message   

  = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
    %div
      = f.label :avatar, 'Avatar'
    %div
      = f.file_field :avatar, class: 'text'
    %div
      = f.label :nickname, 'Name'
    %div
      = f.text_field :nickname, class: 'text'
    %div
      = f.label :introdaction, 'Introdaction'
    %div
      = f.text_area :introdaction, class: 'text'
    %div
      = f.label :birthday, 'Birthday'
    %div
      = f.date_field :birthday, class: 'text'      
    %div
      = f.submit 'Submit', class: 'btn-primary'

app/views/profiles/show.html.haml
.container
  %h2 Profile
  .profile_edit_button
    = link_to 'Edit', edit_profile_path
  
  .profile
    = image_tag current_user.avatar_image, class: 'header_logos', class: 'header_avatar'
    .profile_display_name
      = current_user.display_name
    .profile_birthday
      = current_user.profile&.birthday
  %br
    .profile_introdaction
      = current_user.profile&.introdaction
  

app/views/tasks/edit.html.haml
.container
  %ul
  - @task.errors.full_messages.each do |message|
    %li= message   

  = form_with(model: @task, url: board_task_path(@board, @task), method: 'put', local: true) do |f|
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    %div
      = f.label :limit_date, 'Deadline'
    %div
      = f.date_field :limit_date, class: 'text'
    %div
      = f.label :eyecatch, 'Eyecatch'
    %div
      = f.file_field :eyecatch, class: 'text'      
    %div
      = f.submit 'Submit', class: 'btn-primary'

app/views/tasks/new.html.haml
.container
  %h2 New Card

  %ul
  - @task.errors.full_messages.each do |message|
    %li= message   

  = form_with(model: @task, url: board_tasks_path, local: true) do |f|
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    %div
      = f.label :limit_date, 'Deadline'
    %div
      = f.date_field :limit_date, class: 'text'
    %div
      = f.label :eyecatch, 'Eyecatch'
    %div
      = f.file_field :eyecatch, class: 'text'      
    %div
      = f.submit 'Submit', class: 'btn-primary'

app/views/tasks/show.html.haml
.container

  .card_section
    %h2= @task.title
  
    - if user_signed_in? && current_user.has_written_task?(@task)
      .dropdown
        = image_tag 'Combined Shape.png', class: 'dropbtn'
        .dropdown-content.mini
          = link_to 'Edit', edit_board_task_path(@board, @task)
          = link_to 'Delete', board_task_path(@board, @task), data: { method: 'delete' , confirm: '本当に削除してもよろしいですか？'}

  - if @task.eyecatch.attached?
    .card_image
      = image_tag @task.eyecatch
  .card
    .card_content-task
      = @task.content
  
  %h2
    .comment_title
      Comment
  - @comments.each do |comment|
    .comment
      = image_tag comment.user.avatar_image, class: 'header_avatar'
      .comment_text
        = comment.content
  
  = link_to new_board_task_comment_path(@board, @task) do
    .new-comment
      .new-comment_title
        + Add new comment